# ***************************************************************
# *                 CREATED BY HENGO VISUAL SCRIPT              *
# *    This file is automatically generated and maintained by   *
# *               the Hengo Visual Script tool.                 *
# *       Edit only if you are confident in your changes.       *
# ***************************************************************

extends Node

func function_63(param_63):
	pass


func function_22():
	print("ddd")

var _STATE_CONTROLLER = HengoStateController.new()

const _EVENTS = {}

func _init() -> void:
	_STATE_CONTROLLER.set_states({
		state_1=State1.new(self)
	})

func _ready() -> void:
	if not _STATE_CONTROLLER.current_state:
		_STATE_CONTROLLER.change_state("state_1")

func trigger_event(_event: String) -> void:
	if _EVENTS.has(_event):
		_STATE_CONTROLLER.change_state(_EVENTS[_event])

func _process(delta: float) -> void:
	_STATE_CONTROLLER.static_process(delta)

func _physics_process(delta: float) -> void:
	_STATE_CONTROLLER.static_physics_process(delta)

class State1 extends HengoState:
	func enter() -> void:
		_ref.notify_thread_safe(42.0)
		_ref.function_63("okok")
		if true:
			_ref.set_meta("haha", null)
			_ref.get_node("Testing").my_func_183()[0]
		print(_ref.function_22()[0])
		print(_ref.test_name_2)