#[hengo] res://hengo/save/5651739105259045626.res

# ***************************************************************
# *                 CREATED BY HENGO VISUAL SCRIPT              *
# *    This file is automatically generated and maintained by   *
# *               the Hengo Visual Script tool.                 *
# *       Edit only if you are confident in your changes.       *
# ***************************************************************

extends Sprite2D

var ata = String()
 
var my_var_3912 = String()#ID:3912
var my_var_4138 = String()#ID:4138
var my_var_4199 = String()#ID:4199
var _STATE_CONTROLLER = HengoStateController.new()

const _EVENTS = {}

func _init() -> void:
	_STATE_CONTROLLER.set_states({
		state_1=State1.new(self)
	})

func _ready() -> void:
	if not _STATE_CONTROLLER.current_state:
		_STATE_CONTROLLER.change_state("state_1")

func trigger_event(_event: String) -> void:
	if _EVENTS.has(_event):
		_STATE_CONTROLLER.change_state(_EVENTS[_event])

func _process(delta: float) -> void:
	_STATE_CONTROLLER.static_process(delta)

func _physics_process(delta: float) -> void:
	_STATE_CONTROLLER.static_physics_process(delta)

class State1 extends HengoState:
	func enter() -> void:
		print("ata")
		if false:
			_ref.set_centered(false)
			if false:
				_ref.get_offset()
				_ref.set_flip_v(false)
			else:
				_ref.set_texture(Texture2D.new())
				_ref.set_offset(Vector2(5, 0))
				_ref.set_flip_h(false)
		_ref.set_owner(Node.new())
		_ref.set_flip_v(false)
		for index_3732 in range(0, 0, 1):
			_ref.set_centered(false)
			_ref.set_offset(Vector2(5, 0))
			_ref.set_flip_h(false)
		_ref.set_offset(Vector2(5, 0))
		_ref.set_flip_h(false)