#[hengo] res://hengo/save/3567223492641660476.res

# ***************************************************************
# *                 CREATED BY HENGO VISUAL SCRIPT              *
# *    This file is automatically generated and maintained by   *
# *               the Hengo Visual Script tool.                 *
# *       Edit only if you are confident in your changes.       *
# ***************************************************************

extends Node

 # Variables #

func func_2880016253(a, g):

	return null



var _STATE_CONTROLLER = HengoStateController.new()

const _EVENTS ={}

func _init() -> void:
	_STATE_CONTROLLER.set_states({
		state_1=State1.new(self)
	})

func _ready() -> void:
	if not _STATE_CONTROLLER.current_state:
		_STATE_CONTROLLER.change_state("state_1")
	


func trigger_event(_event: String) -> void:
	if _EVENTS.has(_event):
		_STATE_CONTROLLER.change_state(_EVENTS[_event])

func _process(delta: float) -> void:
	_STATE_CONTROLLER.static_process(delta)


func _physics_process(delta: float) -> void:
	_STATE_CONTROLLER.static_physics_process(delta)

class State1 extends HengoState:
	pass


