#[hengo] res://hengo/save/1990296267774900407.hengo

# ***************************************************************
# *                 CREATED BY HENGO VISUAL SCRIPT              *
# *    This file is automatically generated and maintained by   *
# *               the Hengo Visual Script tool.                 *
# *       Edit only if you are confident in your changes.       *
# ***************************************************************

extends Sprite2D

var var_893438831 = bool()  
var holy_2 = String()  
 
func func_1205940485(dsa):
	return null


func _on_signal_51497076513_signal_(toggled_on):
	pass

var _STATE_CONTROLLER = HengoStateController.new()

const _EVENTS = {}

func _init() -> void:
	_STATE_CONTROLLER.set_states({
		state_1=State1.new(self)
	})

func _ready() -> void:
	if not _STATE_CONTROLLER.current_state:
		_STATE_CONTROLLER.change_state("state_1")
	set_rotation(0.) 
	print(null, null)
func trigger_event(_event: String) -> void:
	if _EVENTS.has(_event):
		_STATE_CONTROLLER.change_state(_EVENTS[_event])

func _process(delta: float) -> void:
	_STATE_CONTROLLER.static_process(delta)

func _physics_process(delta: float) -> void:
	_STATE_CONTROLLER.static_physics_process(delta)

class State1 extends HengoState:
	func enter() -> void:
		print(_ref.holy_2)
		print(Node.new().get_name())
		print(randi_range(0, 0))
		Curve.new().get_point_position(randi_range(0, 0))
		DirAccess.dir_exists_absolute("")
		Control.new().get_position()
		DirAccess.dir_exists_absolute("")
		_ref.holy_2 = "dsadsad"
		BaseButton.new().connect("toggled", _ref._on_signal_51497076513_signal_)
		BaseButton.new().disconnect("toggled", _ref._on_signal_51497076513_signal_)

	func update(delta) -> void:
		Node.new().set_process_input(false)
		_ref.set_clip_children_mode(null, _ref.get_visibility_layer(null))