#[hengo] res://hengo/save/7552240213291941285.hengo

# ***************************************************************
# *                 CREATED BY HENGO VISUAL SCRIPT              *
# *    This file is automatically generated and maintained by   *
# *               the Hengo Visual Script tool.                 *
# *       Edit only if you are confident in your changes.       *
# ***************************************************************

extends Node

var _STATE_CONTROLLER = HengoStateController.new()

const _EVENTS = {}

func _init() -> void:
	_STATE_CONTROLLER.set_states({
		this_is_my_state=ThisIsMyState.new(self)
	})

func _ready() -> void:
	if not _STATE_CONTROLLER.current_state:
		_STATE_CONTROLLER.change_state("this_is_my_state")

func trigger_event(_event: String) -> void:
	if _EVENTS.has(_event):
		_STATE_CONTROLLER.change_state(_EVENTS[_event])

func _process(delta: float) -> void:
	_STATE_CONTROLLER.static_process(delta)

func _physics_process(delta: float) -> void:
	_STATE_CONTROLLER.static_physics_process(delta)

class ThisIsMyState extends HengoState:
	func enter() -> void:
		HengoState.INVALID_PLACEHOLDER