#[hengo] {"comments":[],"connections":[],"debug_symbols":{"2":[6,"cnode"]},"flow_connections":[],"func_list":[],"generals":[],"node_counter":9,"prop_counter":0,"props":[],"state_event_list":["State Event 1"],"state_name_counter":0,"type":"Sprite2D","virtual_cnode_list":[{"flow_connections":[{"to_id":2,"to_idx":0}],"id":1,"input_connections":[],"name":"State","output_connections":[],"position":"Vector2(0, 0)","size":"Vector2(91, 86)","sub_type":36,"type":5},{"flow_connections":[],"id":2,"input_connections":[],"name":"State 1","output_connections":[],"position":"Vector2(7.19057, 265.449)","size":"Vector2(77, 60)","sub_type":35,"type":4,"virtual_cnode_list":[{"flow_connections":[],"id":3,"input_connections":[],"name":"enter","output_connections":[],"position":"Vector2(0, 0)","size":"Vector2(0, 0)","sub_type":9,"type":0},{"flow_connections":[],"id":4,"input_connections":[],"name":"update","output_connections":[],"outputs":[{"name":"delta","type":"float"}],"position":"Vector2(400, 0)","size":"Vector2(0, 0)","sub_type":9,"type":0}]},{"flow_connections":[],"id":5,"input_connections":[],"name":"State 2","output_connections":[],"position":"Vector2(499.828, 288.479)","size":"Vector2(80, 60)","sub_type":35,"type":4,"virtual_cnode_list":[{"flow_connections":[{"to_id":9,"to_idx":0}],"id":6,"input_connections":[],"name":"enter","output_connections":[],"position":"Vector2(0, 0)","size":"Vector2(66, 68)","sub_type":9,"type":0},{"flow_connections":[],"id":7,"input_connections":[],"name":"update","output_connections":[],"outputs":[{"name":"delta","type":"float"}],"position":"Vector2(400, 0)","size":"Vector2(112, 111)","sub_type":9,"type":0},{"category":"native","flow_connections":[],"id":9,"input_connections":[],"inputs":[{"code_value":"\"Testingg\"","name":"content","type":"String","value":"Testingg"}],"name":"print","output_connections":[],"position":"Vector2(-106.403, 408.57)","size":"Vector2(239, 128)","sub_type":1,"type":0}]},{"flow_connections":[{"to_id":5,"to_idx":0}],"id":8,"input_connections":[],"name":"State Event 1","output_connections":[],"position":"Vector2(476.798, 41.159)","size":"Vector2(125, 60)","sub_type":37,"type":6}]}

# ***************************************************************
# *                 CREATED BY HENGO VISUAL SCRIPT              *
# *    This file is automatically generated and maintained by   *
# *               the Hengo Visual Script tool.                 *
# *       Edit only if you are confident in your changes.       *
# ***************************************************************

extends Sprite2D

 # Variables #

var _STATE_CONTROLLER = HengoStateController.new()

const _EVENTS = {
	state_event_1 = "state_2"
}

func _init() -> void:
	_STATE_CONTROLLER.set_states({
		state_1 = State1.new(self),
		state_2 = State2.new(self)
	})

func _ready() -> void:
	if not _STATE_CONTROLLER.current_state:
		_STATE_CONTROLLER.change_state("state_1")


func trigger_event(_event: String) -> void:
	if _EVENTS.has(_event):
		_STATE_CONTROLLER.change_state(_EVENTS[_event])
	

func _process(delta: float) -> void:
	_STATE_CONTROLLER.static_process(delta)


func _physics_process(delta: float) -> void:
	_STATE_CONTROLLER.static_physics_process(delta)


# Functions
class State1 extends HengoState:
	func enter() -> void:
		print('xx')
		#hen_dbg#EngineDebugger.send_message('hengo:debug_state', [99])
		pass


class State2 extends HengoState:
	func enter() -> void:
		#hen_dbg#var __hen_id__: float = 0.
		print("Testingg")
		#hen_dbg#__hen_id__ += 2
		#hen_dbg#EngineDebugger.send_message('hengo:cnode', [__hen_id__])
		#hen_dbg#EngineDebugger.send_message('hengo:debug_state', [99])
