#[hengo] res://hengo/save/6143492320953670987.hengo

# ***************************************************************
# *                 CREATED BY HENGO VISUAL SCRIPT              *
# *    This file is automatically generated and maintained by   *
# *               the Hengo Visual Script tool.                 *
# *       Edit only if you are confident in your changes.       *
# ***************************************************************

extends Node

func func_30550403(name_0, name_1):
	pass


var _STATE_CONTROLLER = HengoStateController.new()

const _EVENTS = {}

func _init() -> void:
	_STATE_CONTROLLER.set_states({
		state_1 = State1.new(self)
	})

func _ready() -> void:
	if not _STATE_CONTROLLER.current_state:
		_STATE_CONTROLLER.change_state("state_1")

func trigger_event(_event: String) -> void:
	if _EVENTS.has(_event):
		_STATE_CONTROLLER.change_state(_EVENTS[_event])

func _process(delta: float) -> void:
	_STATE_CONTROLLER.static_process(delta)

func _physics_process(delta: float) -> void:
	_STATE_CONTROLLER.static_physics_process(delta)

class State1 extends HengoState:
	func enter() -> void:
		print(null)
		if false:
			print(null)
			if false:
				if false:
					pass
				print(null)
			else:
				if false:
					print(null)
				print(null)
			print(null)
			if _ref.get_node("").has_node(""):
				pass
			print(null)
		else:
			print(_ref.get_name())
		_ref.func_30550403(_ref.has_node(""), _ref.get_path())
