#[hengo] {"comments":[],"connections":[],"debug_symbols":{},"flow_connections":[],"func_list":[],"generals":[],"node_counter":5,"prop_counter":0,"props":[],"side_bar_list":{"func_list":[],"macro_list":[],"signal_list":[],"var_list":[]},"state_event_list":[],"type":"Sprite2D","virtual_cnode_list":[{"flow_connections":[],"id":1,"input_connections":[],"name":"State","output_connections":[],"position":"Vector2(0, 0)","size":"Vector2(91, 92)","sub_type":36,"type":6},{"flow_connections":[{"to_id":3,"to_idx":0}],"id":2,"input_connections":[],"inputs":[{"category":"default_value","code_value":"_ref.","is_ref":true,"name":"Sprite2D","type":"Sprite2D"}],"name":"_ready","output_connections":[],"position":"Vector2(437.038, 12.639)","size":"Vector2(210, 112)","sub_type":44,"type":0},{"category":"native","flow_connections":[],"id":3,"input_connections":[],"inputs":[{"category":"default_value","code_value":"null","name":"content","type":"Variant","value":"null"}],"name":"print","output_connections":[],"position":"Vector2(438.942, 437.274)","size":"Vector2(200, 112)","sub_type":1,"type":0},{"flow_connections":[{"to_id":3,"to_idx":0}],"id":4,"input_connections":[],"inputs":[{"category":"default_value","code_value":"_ref.","is_ref":true,"name":"Sprite2D","type":"Sprite2D"},{"category":"default_value","code_value":"0.","name":"delta","type":"float","value":"0."}],"name":"_process","output_connections":[],"position":"Vector2(987.581, 0.357783)","size":"Vector2(210, 160)","sub_type":44,"type":0},{"flow_connections":[{"to_id":3,"to_idx":0}],"id":5,"input_connections":[],"inputs":[{"category":"default_value","code_value":"_ref.","is_ref":true,"name":"Sprite2D","type":"Sprite2D"},{"category":"default_value","code_value":"0.","name":"delta","type":"float","value":"0."}],"name":"_physics_process","output_connections":[],"position":"Vector2(1313.08, 27.4831)","size":"Vector2(210, 160)","sub_type":44,"type":0}]}

# ***************************************************************
# *                 CREATED BY HENGO VISUAL SCRIPT              *
# *    This file is automatically generated and maintained by   *
# *               the Hengo Visual Script tool.                 *
# *       Edit only if you are confident in your changes.       *
# ***************************************************************

extends Sprite2D

 # Variables #

var _STATE_CONTROLLER = HengoStateController.new()

const _EVENTS ={}

func _init() -> void:
	_STATE_CONTROLLER.set_states({

	})

func _ready() -> void:
	if not _STATE_CONTROLLER.current_state:
		_STATE_CONTROLLER.change_state("")
	
	print(null)

func trigger_event(_event: String) -> void:
	if _EVENTS.has(_event):
		_STATE_CONTROLLER.change_state(_EVENTS[_event])

func _process(delta: float) -> void:
	_STATE_CONTROLLER.static_process(delta)

func _physics_process(delta: float) -> void:
	_STATE_CONTROLLER.static_physics_process(delta)


