#[hengo] {"comments":[],"connections":[],"debug_symbols":{"2.0":[3,"cnode"]},"flow_connections":[],"func_list":[],"generals":[],"node_counter":13,"prop_counter":0,"props":[],"state_event_list":[],"state_name_counter":0,"type":"Sprite2D","virtual_cnode_list":[{"flow_connections":[{"to_id":2,"to_idx":0}],"id":1,"input_connections":[],"name":"State","output_connections":[],"position":"Vector2(0, 0)","size":"Vector2(91, 84)","sub_type":36,"type":5},{"flow_connections":[],"id":7,"input_connections":[],"name":"State 1","output_connections":[],"position":"Vector2(-268.149, 530.016)","size":"Vector2(77, 60)","sub_type":35,"type":4,"virtual_cnode_list":[{"flow_connections":[],"id":8,"input_connections":[],"name":"enter","output_connections":[],"position":"Vector2(0, 0)","size":"Vector2(0, 0)","sub_type":9,"type":0},{"flow_connections":[],"id":9,"input_connections":[],"name":"update","output_connections":[],"outputs":[{"name":"delta","type":"float"}],"position":"Vector2(400, 0)","size":"Vector2(0, 0)","sub_type":9,"type":0}]},{"flow_connections":[],"id":10,"input_connections":[],"name":"State 1","output_connections":[],"position":"Vector2(355.042, 514.628)","size":"Vector2(77, 60)","sub_type":35,"type":4,"virtual_cnode_list":[{"flow_connections":[],"id":11,"input_connections":[],"name":"enter","output_connections":[],"position":"Vector2(0, 0)","size":"Vector2(0, 0)","sub_type":9,"type":0},{"flow_connections":[],"id":12,"input_connections":[],"name":"update","output_connections":[],"outputs":[{"name":"delta","type":"float"}],"position":"Vector2(400, 0)","size":"Vector2(0, 0)","sub_type":9,"type":0}]},{"flow_connections":[{"to_id":7,"to_idx":0},{"to_id":10,"to_idx":0}],"id":2,"input_connections":[],"name":"State 1","output_connections":[],"position":"Vector2(7.88089, 262.041)","size":"Vector2(150, 92)","sub_type":35,"type":4,"virtual_cnode_list":[{"flow_connections":[{"to_id":5,"to_idx":0}],"id":3,"input_connections":[],"name":"enter","output_connections":[],"position":"Vector2(0, 0)","size":"Vector2(66, 68)","sub_type":9,"type":0},{"flow_connections":[],"id":4,"input_connections":[],"name":"update","output_connections":[],"outputs":[{"name":"delta","type":"float"}],"position":"Vector2(400, 0)","size":"Vector2(112, 111)","sub_type":9,"type":0},{"category":"native","flow_connections":[{"to_id":6,"to_idx":0}],"id":5,"input_connections":[{"from_idx":0,"from_vc_id":13,"idx":0}],"inputs":[{"code_value":"null","name":"content","type":"Variant"}],"name":"print","output_connections":[],"position":"Vector2(-55.4279, 243.792)","size":"Vector2(135, 111)","sub_type":1,"type":0},{"category":"native","flow_connections":[],"id":6,"input_connections":[],"inputs":[{"code_value":"\"\"","name":"content","type":"String"}],"name":"print","output_connections":[],"position":"Vector2(335.271, 652.287)","size":"Vector2(215, 116)","sub_type":1,"type":0},{"flow_connections":[],"id":13,"input_connections":[],"inputs":[{"code_value":"_ref","is_ref":true,"name":"Sprite2D","type":"Sprite2D"}],"name":"get_frame_coords","output_connections":[],"outputs":[{"name":"","type":"Vector2i"}],"position":"Vector2(-579.328, 426.118)","size":"Vector2(259, 112)","sub_type":0,"type":0}]}]}

# ***************************************************************
# *                 CREATED BY HENGO VISUAL SCRIPT              *
# *    This file is automatically generated and maintained by   *
# *               the Hengo Visual Script tool.                 *
# *       Edit only if you are confident in your changes.       *
# ***************************************************************

extends Sprite2D

 # Variables #

var _STATE_CONTROLLER = HengoStateController.new()

const _EVENTS ={}

func _init() -> void:
	_STATE_CONTROLLER.set_states({
		state_1=State1.new(self, {
			flow_0="state_1",
			flow_1="state_1"
		})
	})

func _ready() -> void:
	if not _STATE_CONTROLLER.current_state:
		_STATE_CONTROLLER.change_state("state_1")

func trigger_event(_event: String) -> void:
	if _EVENTS.has(_event):
		_STATE_CONTROLLER.change_state(_EVENTS[_event])

func _process(delta: float) -> void:
	_STATE_CONTROLLER.static_process(delta)



func _physics_process(delta: float) -> void:
	_STATE_CONTROLLER.static_physics_process(delta)








# Functions
class State1 extends HengoState:
	func enter() -> void:
		#hen_dbg#var __hen_id__: float = 0.

		print(_ref.get_frame_coords())
		print("")
		#hen_dbg#__hen_id__ += 2.0
		#hen_dbg#EngineDebugger.send_message('hengo:cnode', [__hen_id__])
		#hen_dbg#EngineDebugger.send_message('hengo:debug_state', [99])



