@tool
class_name HenCodeGeneration extends Node

var flow_id: int = 0
var flows_refs: Dictionary = {}
var flow_errors: Array[Dictionary] = []


func get_flow_id() -> int:
	flow_id += 1
	return flow_id


func get_code(_data: HenSaveData, _build_preview: bool = false) -> String:
	var refs: HenTypeReferences = HenTypeReferences.new()
	var code: String = ''

	(Engine.get_singleton(&'Global') as HenGlobal).GENERATE_PREVIEW_CODE = _build_preview
	(Engine.get_singleton(&'CodeGeneration') as HenCodeGeneration).flow_errors.clear()

	code += _get_start(_data)
	code += HenGeneratorSignal.get_signals_code(_data)
	code += HenGeneratorVariable.get_variables_code(_data)
	code += HenGeneratorFunc.get_functions_code(_data)
	code += HenGeneratorSignalCallback.get_signals_callback_code(_data)
	code += HenGeneratorBase.get_base_script_code(_data, refs)

	return code

#
#
#
#
#
#
func _get_start(_data: HenSaveData) -> String:
	var global: HenGlobal = Engine.get_singleton(&'Global')
	# reseting macro use self condition
	global.USE_MACRO_USE_SELF = false
	global.USE_MACRO_REF = false

	return '# ***************************************************************
# *                 CREATED BY HENGO VISUAL SCRIPT              *
# *    This file is automatically generated and maintained by   *
# *               the Hengo Visual Script tool.                 *
# *       Edit only if you are confident in your changes.       *
# ***************************************************************\n\nextends {0}\n\n'.format([_data.identity.type])