@tool
class_name HenCodeGeneration extends Node

var flow_id: int = 0
var flows_refs: Dictionary = {}
var flow_errors: Array[Dictionary] = []


func reset() -> void:
	flow_id = 0
	flows_refs.clear()
	flow_errors.clear()


func get_flow_id() -> int:
	flow_id += 1
	return flow_id


func get_code(_save_data: HenSaveData, _build_preview: bool = false) -> String:
	var refs: HenTypeReferences = HenTypeReferences.new()
	var code: String = ''

	(Engine.get_singleton(&'Global') as HenGlobal).GENERATE_PREVIEW_CODE = _build_preview
	(Engine.get_singleton(&'CodeGeneration') as HenCodeGeneration).flow_errors.clear()

	code += _get_start(_save_data)
	code += HenGeneratorSignal.get_signals_code(_save_data)
	code += HenGeneratorVariable.get_variables_code(_save_data)
	code += HenGeneratorFunc.get_functions_code(_save_data)
	code += HenGeneratorSignalCallback.get_signals_callback_code(_save_data)
	code += HenGeneratorBase.get_base_script_code(_save_data, refs)

	return code

#
#
#
#
#
#
func _get_start(_save_data: HenSaveData) -> String:
	var global: HenGlobal = Engine.get_singleton(&'Global')
	# reseting macro use self condition
	global.USE_MACRO_USE_SELF = false
	global.USE_MACRO_REF = false

	var start_code: String = '# ***************************************************************\n'
	start_code += '# *                 CREATED BY HENGO VISUAL SCRIPT              *\n'
	start_code += '# *    This file is automatically generated and maintained by   *\n'
	start_code += '# *               the Hengo Visual Script tool.                 *\n'
	start_code += '# *       Edit only if you are confident in your changes.       *\n'
	start_code += '# ***************************************************************\n\n'
	start_code += 'extends {0}\n\n'.format([_save_data.identity.type])

	if global.SETTINGS.debug_compilation:
		start_code += 'const HENGO_DEBUG_SCRIPT_ID = &\'{0}\'\n\n'.format([_save_data.identity.id])

	return start_code